version: '3.7'

networks:
  default:
    attachable: true
    ipam:
      config:
        - subnet: 10.1.1.0/24

services:
  gateway:
    image: $COMPOSE_REGISTRY-gateway
    build: gateway
    ports:
      - 80:80
      - 1080:1080
    networks:
      default:
        aliases:
          - registry.docker.internal
          - ui.registry.docker.internal
          - ui.docker.internal
          - proxy.internal
    restart: always

  ui:
    image: portainer/portainer
    command: -H tcp://node1.manager.docker.internal:2375
    ports:
      - 9007:9000
    networks:
      default:
        aliases:
          - service.ui.docker.internal
    restart: always
    volumes:
      - $COMPOSE_DATADIR/ui.docker:/data

  registry:
    image: registry
    ports:
      - 9008:5000
    env_file: .env
    networks:
      default:
        aliases:
          - service.registry.docker.internal
    restart: always
    volumes:
      - $COMPOSE_DATADIR/registry:/var/lib/registry

  registry_frontend:
    image: konradkleine/docker-registry-frontend:v2
    ports:
      - 9009:80
    environment:
      - ENV_DOCKER_REGISTRY_HOST=registry
      - ENV_DOCKER_REGISTRY_PORT=5000
    networks:
      default:
        aliases:
          - ui.registry.docker.internal
    restart: always

  gitlab:
    image: gitlab/gitlab-ce:latest
    ports:
      - '9010:22'
      - '9011:80'
      - '9012:443'
    volumes:
      - $COMPOSE_DATADIR/gitlab/data:/var/opt/gitlab
      - $COMPOSE_DATADIR/gitlab/logs:/var/log/gitlab
      - $COMPOSE_DATADIR/gitlab/config:/etc/gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: "from_file('/omnibus_config.rb')"
    configs:
      - source: gitlab
        target: /omnibus_config.rb
    secrets:
      - gitlab_root_password
    networks:
      default:
        aliases:
          - gitlab.internal
          - ui.gitlab.internal

  gitlab-runner:
    image: gitlab/gitlab-runner:alpine
    deploy:
      mode: replicated
      replicas: 1

  mssql:
    image: registry.cn-beijing.aliyuncs.com/nianwu/mcr.microsoft.com-mssql-server:2019-CU4-ubuntu-16.04
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: 'QWER1234!!!!'
    ports:
      - 9013:1433
    networks:
      default:
        aliases:
          - mssql.internal

configs:
  gitlab:
    file: ./gitlab/gitlab.rb
secrets:
  gitlab_root_password:
    file: ./gitlab/root_password.txt
