version: "3.7"

networks:
  default:
    attachable: true
    ipam:
      config:
        - subnet: 10.1.1.0/24
    attachable: true

services:
  gateway:
    image: gateway
    build: gateway
    ports:
      - 80:80
      - 1080:1080
    networks:
      default:
        aliases:
          - registry.docker.internal
          - ui.docker.internal
          - proxy.internal
    restart: always

  ui:
    image: portainer/portainer
    command: -H tcp://node1.manager.docker.internal:2375
    ports:
      - 9007:9000
    networks:
      default:
        aliases:
          - service.ui.docker.internal
    restart: always
    volumes: 
      - ~/data/ui.docker:/data

  registry:
    image: registry
    ports:
      - 9008:5000
    networks:
      default:
        aliases:
          - service.registry.docker.internal
    restart: always
    volumes: 
      - ~/data/registry:/var/lib/registry

  registry_frontend:
    image: konradkleine/docker-registry-frontend:v2
    ports:
      - 9009:80
    environment:
      - ENV_DOCKER_REGISTRY_HOST=registry
      - ENV_DOCKER_REGISTRY_PORT=5000
    networks:
      default:
        aliases:
          - ui.registry.docker.internal
    restart: always
