version: '3.7'

services:
  manager_1:
    image: docker:19.03.11-dind
    privileged: true
    container_name: manager_1
    environment:
      DOCKER_TLS_CERTDIR: # 证书为空, 即不使用https
    hostname: manager_1
    ports:
      - 9001:2375
    networks:
      nw_utility_default:
        aliases:
          - docker
          - node1.manager.docker.internal
          - manager.docker.internal
          - docker.internal
      default_swarms:
        ipv4_address: $COMPOSE_SWARM_SUBNET.21
    restart: always
    volumes:
      - $COMPOSE_DATADIR/swarm1/manager_1:/var/lib/docker

  manager_2:
    image: docker:19.03.11-dind
    privileged: true
    container_name: manager_2
    environment:
      DOCKER_TLS_CERTDIR:
    hostname: manager_2
    ports:
      - 9002:2375
    networks:
      nw_utility_default:
        aliases:
          - docker
          - node2.manager.docker.internal
          - manager.docker.internal
          - docker.internal
      default_swarms:
        ipv4_address: $COMPOSE_SWARM_SUBNET.22
    restart: always
    volumes:
      - $COMPOSE_DATADIR/swarm1/manager_2:/var/lib/docker

  manager_3:
    image: docker:19.03.11-dind
    privileged: true
    container_name: manager_3
    environment:
      DOCKER_TLS_CERTDIR:
    hostname: manager_3
    ports:
      - 9003:2375
    networks:
      nw_utility_default:
        aliases:
          - docker
          - node3.manager.docker.internal
          - manager.docker.internal
          - docker.internal
      default_swarms:
        ipv4_address: $COMPOSE_SWARM_SUBNET.23
    restart: always
    volumes:
      - $COMPOSE_DATADIR/swarm1/manager_3:/var/lib/docker

  worker_1:
    image: docker:19.03.11-dind
    privileged: true
    container_name: worker_1
    environment:
      DOCKER_TLS_CERTDIR:
    hostname: worker_1
    ports:
      - 9004:2375
    networks:
      nw_utility_default:
        aliases:
          - docker
          - node1.worker.docker.internal
          - worker.docker.internal
          - docker.internal
      default_swarms:
        ipv4_address: $COMPOSE_SWARM_SUBNET.24
    restart: always
    volumes:
      - $COMPOSE_DATADIR/swarm1/worker_1:/var/lib/docker

  worker_2:
    image: docker:19.03.11-dind
    privileged: true
    container_name: worker_2
    environment:
      DOCKER_TLS_CERTDIR:
    hostname: worker_2
    ports:
      - 9005:2375
    networks:
      nw_utility_default:
        aliases:
          - docker
          - node2.worker.docker.internal
          - worker.docker.internal
          - docker.internal
      default_swarms:
        ipv4_address: $COMPOSE_SWARM_SUBNET.25
    restart: always
    volumes:
      - $COMPOSE_DATADIR/swarm1/worker_2:/var/lib/docker

  worker_3:
    image: docker:19.03.11-dind
    privileged: true
    container_name: worker_3
    environment:
      DOCKER_TLS_CERTDIR:
    hostname: worker_3
    ports:
      - 9006:2375
    networks:
      nw_utility_default:
        aliases:
          - docker
          - node3.worker.docker.internal
          - worker.docker.internal
          - docker.internal
      default_swarms:
        ipv4_address: $COMPOSE_SWARM_SUBNET.26
    restart: always
    volumes:
      - $COMPOSE_DATADIR/swarm1/worker_3:/var/lib/docker

networks:
  default_swarms:
    attachable: true
    ipam:
      config:
        - subnet: $COMPOSE_SWARM_SUBNET.0/24
  nw_utility_default:
    external: true