version: '3.7'

services:
  gateway:
    image: gateway
    build: .
    ports:
      - 80:80
      - 1080:1080
    networks: 
      default:
        aliases:
          - registry.docker.internal
          - ui.docker.internal
          - proxy.internal

networks:
  default:
    attachable: true
    ipam:
      config:
        - subnet: 10.1.1.0/24
