version: '3.7'

services:
  gateway:
    image: gateway
    build: .
    ports:
      - 80:80

networks:
  default:
    attachable: true
    ipam:
      config:
        - subnet: 10.1.1.0/24
