version: '3.7'
services:
  registry:
    image: registry
    ports:
      - 30007:5000
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 1
    networks:
      gateway_default:
        aliases:
          - service.registry.docker.internal

  registry_frontend:
    image: konradkleine/docker-registry-frontend:v2
    ports:
      - 9007:80
    environment:
      - ENV_DOCKER_REGISTRY_HOST=registry
      - ENV_DOCKER_REGISTRY_PORT=5000
    networks:
      gateway_default:
        aliases:
          - ui.registry.docker.internal

networks:
  gateway_default:
    external: true
