version: "3.7"

services:
  reverse_proxy:
    image: reverse_proxy
    build:
      context: ./
    deploy:
      mode: global
    ports:
      - "80:80"
      - "2375:2375"
      - "8080:8080"
