FROM ubuntu:18.04-zsh

RUN wget -q https://raw.githubusercontent.com/dapr/cli/master/install/install.sh -O - | /bin/bash \
    && curl -fsSL https://get.docker.com -o get-docker.sh \
    && sh get-docker.sh
